# Generated by Django 3.1.7 on 2021-04-01 04:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_empleados'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('persona_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='home.persona')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
            ],
            bases=('home.persona',),
        ),
        migrations.RemoveConstraint(
            model_name='persona',
            name='edad_mayor_18',
        ),
        migrations.AddConstraint(
            model_name='persona',
            constraint=models.CheckConstraint(check=models.Q(edad__gte=18), name='edad_gte_18'),
        ),
    ]
